[package]
name = "embed_capi"
version = "0.0.1"
authors = ["Geoffroy Couprie <geo.couprie@gmail.com>"]

[lib]
name = "embed_capi"
crate-type = ["staticlib"]

[dependencies]
libc = "0"

[dependencies.embed]
path = "../"
